spring:
  application:
    name: news-ms
  profiles:
    active: test


  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      import-check:
        enabled: false

  liquibase:
    enabled: false

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

cache:
  enabled: true
  algorithm: LRU
  size: 350

server:
  port: 64102

jwt:
  secret: dfiogudoifguoidfgiodufgiodufgiodufgiod
