spring:
  application:
    name: news-ms
  profiles:
    active: test

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      import-check:
        enabled: false

  liquibase:
    enabled: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 0
