version: "3"

services:

  usersdb:
    container_name: users_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${USERS_DB_PASSWORD}
    env_file:
      - .env.production


  cache:
    container_name: redis-cache
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"

  elastic:
    container_name: full-text-search-elasticsearch
    image: elasticsearch:8.15.3
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"




