version: "3.7"

services:

  usersdb:
    container_name: users_db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env.production

  newsdb:
    container_name: news_db
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env.production


  cache:
    container_name: redis-cache
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"

  elastic:
    container_name: full-text-search-elasticsearch
    image: elasticsearch:7.17.25
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elastic
      - ELASTIC_USERNAME=elastic

    ports:
      - "9200:9200"
      - "9300:9300"

#networks:
#  news-system:
#    driver: bridge




