spring:
  application:
    name: config-server

  cloud:
    config:
      discovery:
        service-id: config-server
      server:
        git:
          uri: https://github.com/ZemichPS/sadovod-application-config
          skipSslValidation: true
          force-pull: true
          ignore-local-ssh-settings: true
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false

server:
  port: 8888
